Fix warning by the compiler, probably caused by a bad conflict resolution
qshakerecognizer.cpp:161:28: error: expression result unused [-Werror,-Wunused-value]

The statement was unused, the last branch of an || that was removed in
fb06538f.

Change-Id: I4badb3e5f4272086d44004b9beaca330f8ed7ab6
Reviewed-by: Lorn Potter <lorn.potter@jollamobile.com>